using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vargainc.Timm.REST.ViewModel
{
    public class CampaignSummaryMapOption
    {
        //googleKey:AIzaSyAKdtxTHEA7_knbSLYAw8iQDrKQ70_K7uI
        //targetMethod:
        //gTUDotsRadii:5
        //PenetrationColors[]:20
        //PenetrationColors[]:40
        //PenetrationColors[]:60
        //PenetrationColors[]:80
        //baseUrl:http://52.8.230.211/201601/api/
        //mapUrl:http://54.67.112.52/map/
        //imgUrl:http://ec2-54-67-112-52.us-west-1.compute.amazonaws.com/mapimg/
        //campaignId:45
        //suppressCover:false
        //suppressCampaign:false
        //suppressCampaignSummary:false
        //suppressNDAInCampaign:false
        //suppressSubMap:false
        //suppressSubMapCountDetail:false
        //suppressNDAInSubMap:false
        //suppressDMap:true
        //showPenetrationColors:true
        //suppressLocations:false
        //suppressRadii:false
        //suppressGTU:false
        //suppressNDAInDMap:false
        //btnCheckAllDMap:false
        //type:Campaign
        //mapType:ROADMAP

    }
    public class SubmapMapOption
    {
        //googleKey:AIzaSyAKdtxTHEA7_knbSLYAw8iQDrKQ70_K7uI
        //targetMethod:
        //gTUDotsRadii:5
        //PenetrationColors[]:20
        //PenetrationColors[]:40
        //PenetrationColors[]:60
        //PenetrationColors[]:80
        //baseUrl:http://52.8.230.211/201601/api/
        //mapUrl:http://54.67.112.52/map/
        //imgUrl:http://ec2-54-67-112-52.us-west-1.compute.amazonaws.com/mapimg/
        //campaignId:45
        //suppressCover:false
        //suppressCampaign:false
        //suppressCampaignSummary:false
        //suppressNDAInCampaign:false
        //suppressSubMap:false
        //suppressSubMapCountDetail:false
        //suppressNDAInSubMap:false
        //suppressDMap:true
        //showPenetrationColors:true
        //suppressLocations:false
        //suppressRadii:false
        //suppressGTU:false
        //suppressNDAInDMap:false
        //btnCheckAllDMap:false
        //submapId:434
        //type:SubMap
        //mapType:HYBRID

    }
    public class DmapMapOption
    {
        //googleKey:AIzaSyAKdtxTHEA7_knbSLYAw8iQDrKQ70_K7uI
        //targetMethod:
        //gTUDotsRadii:5
        //PenetrationColors[]:20
        //PenetrationColors[]:40
        //PenetrationColors[]:60
        //PenetrationColors[]:80
        //baseUrl:http://52.8.230.211/201601/api/
        //mapUrl:http://54.67.112.52/map/
        //imgUrl:http://ec2-54-67-112-52.us-west-1.compute.amazonaws.com/mapimg/
        //campaignId:41
        //suppressCover:true
        //suppressCampaign:true
        //suppressCampaignSummary:true
        //suppressNDAInCampaign:true
        //suppressSubMap:true
        //suppressSubMapCountDetail:true
        //suppressNDAInSubMap:true
        //suppressDMap:false
        //suppressGTU:true
        //suppressNDAInDMap:true
        //customSubMapPenetrationColors:false
        //suppressLocations:true
        //suppressRadii:true
        //mapType:ROADMAP
        //zoom:0
        //showPenetrationColors:false
        //btnCheckAllDMap:false
        //submapId:365
        //type:Distribute
        //dmapId:327
    }
    public class GtuReportMapOption
    {
        //googleKey:AIzaSyAKdtxTHEA7_knbSLYAw8iQDrKQ70_K7uI
        //targetMethod:
        //gTUDotsRadii:5
        //PenetrationColors[]:20
        //PenetrationColors[]:40
        //PenetrationColors[]:60
        //PenetrationColors[]:80
        //baseUrl:http://52.8.230.211/201601/api/
        //mapUrl:http://54.67.112.52/map/
        //imgUrl:http://ec2-54-67-112-52.us-west-1.compute.amazonaws.com/mapimg/
        //campaignId:44
        //suppressCover:false
        //suppressCampaign:false
        //suppressCampaignSummary:false
        //suppressNDAInCampaign:false
        //suppressSubMap:false
        //suppressSubMapCountDetail:false
        //suppressNDAInSubMap:false
        //suppressDMap:false
        //suppressGTU:false
        //showPenetrationColors:true
        //suppressLocations:false
        //suppressRadii:false
        //mapType:HYBRID
        //suppressNDAInDMap:false
        //btnCheckAllDMap:false
        //submapId:433
        //type:DMap
        //dmapId:266
    }
}