USE [timm201601]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER TABLE [dbo].[users]
ADD 
	[Token] [nvarchar](200) NULL,
	[LastLoginTime] [datetime] NULL
 
GO

CREATE NONCLUSTERED INDEX [IX_Token] ON [dbo].[users]
(
	[Token] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO