<?xml version="1.0" encoding="utf-8"?>
<Database Name="GTUTracking" Class="GTUTrackDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SHILX\MSSQL2008;Initial Catalog=GTUTracking;User ID=sa" SettingsObjectName="GTU.DataLayer.Properties.Settings" SettingsPropertyName="GTUTrackingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TrackItem" Member="TrackItems">
    <Type Name="TrackItem">
      <Column Name="TrackId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UniqueId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="longitude" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SendTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InDeliverable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="InNonDeliverable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="StayAlarm" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>