//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace TIMM.GPS.ControlCenter.LocationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="TIMM.Website.SilverlightServices", ConfigurationName="LocationService.LocationService")]
    public interface LocationService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="TIMM.Website.SilverlightServices/LocationService/PointInPolygon", ReplyAction="TIMM.Website.SilverlightServices/LocationService/PointInPolygonResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<double>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<double>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<System.Collections.ObjectModel.ObservableCollection<object>, System.Collections.ObjectModel.ObservableCollection<double>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<object>>))]
        System.IAsyncResult BeginPointInPolygon(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<double>> coordinates, System.Collections.ObjectModel.ObservableCollection<double> point, System.Collections.ObjectModel.ObservableCollection<object> gti, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<object> EndPointInPolygon(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="TIMM.Website.SilverlightServices/LocationService/PointsInPolygon", ReplyAction="TIMM.Website.SilverlightServices/LocationService/PointsInPolygonResponse")]
        System.IAsyncResult BeginPointsInPolygon(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<double>> coordinates, System.Collections.Generic.Dictionary<System.Collections.ObjectModel.ObservableCollection<object>, System.Collections.ObjectModel.ObservableCollection<double>> points, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<object>> EndPointsInPolygon(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="TIMM.Website.SilverlightServices/LocationService/SendMail", ReplyAction="TIMM.Website.SilverlightServices/LocationService/SendMailResponse")]
        System.IAsyncResult BeginSendMail(string to, string subject, string body, string attachName, byte[] attach, System.AsyncCallback callback, object asyncState);
        
        void EndSendMail(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LocationServiceChannel : TIMM.GPS.ControlCenter.LocationService.LocationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PointInPolygonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PointInPolygonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<object> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<object>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PointsInPolygonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PointsInPolygonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<object>> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<object>>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocationServiceClient : System.ServiceModel.ClientBase<TIMM.GPS.ControlCenter.LocationService.LocationService>, TIMM.GPS.ControlCenter.LocationService.LocationService {
        
        private BeginOperationDelegate onBeginPointInPolygonDelegate;
        
        private EndOperationDelegate onEndPointInPolygonDelegate;
        
        private System.Threading.SendOrPostCallback onPointInPolygonCompletedDelegate;
        
        private BeginOperationDelegate onBeginPointsInPolygonDelegate;
        
        private EndOperationDelegate onEndPointsInPolygonDelegate;
        
        private System.Threading.SendOrPostCallback onPointsInPolygonCompletedDelegate;
        
        private BeginOperationDelegate onBeginSendMailDelegate;
        
        private EndOperationDelegate onEndSendMailDelegate;
        
        private System.Threading.SendOrPostCallback onSendMailCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public LocationServiceClient() {
        }
        
        public LocationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<PointInPolygonCompletedEventArgs> PointInPolygonCompleted;
        
        public event System.EventHandler<PointsInPolygonCompletedEventArgs> PointsInPolygonCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SendMailCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TIMM.GPS.ControlCenter.LocationService.LocationService.BeginPointInPolygon(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<double>> coordinates, System.Collections.ObjectModel.ObservableCollection<double> point, System.Collections.ObjectModel.ObservableCollection<object> gti, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPointInPolygon(coordinates, point, gti, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<object> TIMM.GPS.ControlCenter.LocationService.LocationService.EndPointInPolygon(System.IAsyncResult result) {
            return base.Channel.EndPointInPolygon(result);
        }
        
        private System.IAsyncResult OnBeginPointInPolygon(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<double>> coordinates = ((System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<double>>)(inValues[0]));
            System.Collections.ObjectModel.ObservableCollection<double> point = ((System.Collections.ObjectModel.ObservableCollection<double>)(inValues[1]));
            System.Collections.ObjectModel.ObservableCollection<object> gti = ((System.Collections.ObjectModel.ObservableCollection<object>)(inValues[2]));
            return ((TIMM.GPS.ControlCenter.LocationService.LocationService)(this)).BeginPointInPolygon(coordinates, point, gti, callback, asyncState);
        }
        
        private object[] OnEndPointInPolygon(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<object> retVal = ((TIMM.GPS.ControlCenter.LocationService.LocationService)(this)).EndPointInPolygon(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPointInPolygonCompleted(object state) {
            if ((this.PointInPolygonCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PointInPolygonCompleted(this, new PointInPolygonCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PointInPolygonAsync(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<double>> coordinates, System.Collections.ObjectModel.ObservableCollection<double> point, System.Collections.ObjectModel.ObservableCollection<object> gti) {
            this.PointInPolygonAsync(coordinates, point, gti, null);
        }
        
        public void PointInPolygonAsync(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<double>> coordinates, System.Collections.ObjectModel.ObservableCollection<double> point, System.Collections.ObjectModel.ObservableCollection<object> gti, object userState) {
            if ((this.onBeginPointInPolygonDelegate == null)) {
                this.onBeginPointInPolygonDelegate = new BeginOperationDelegate(this.OnBeginPointInPolygon);
            }
            if ((this.onEndPointInPolygonDelegate == null)) {
                this.onEndPointInPolygonDelegate = new EndOperationDelegate(this.OnEndPointInPolygon);
            }
            if ((this.onPointInPolygonCompletedDelegate == null)) {
                this.onPointInPolygonCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPointInPolygonCompleted);
            }
            base.InvokeAsync(this.onBeginPointInPolygonDelegate, new object[] {
                        coordinates,
                        point,
                        gti}, this.onEndPointInPolygonDelegate, this.onPointInPolygonCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TIMM.GPS.ControlCenter.LocationService.LocationService.BeginPointsInPolygon(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<double>> coordinates, System.Collections.Generic.Dictionary<System.Collections.ObjectModel.ObservableCollection<object>, System.Collections.ObjectModel.ObservableCollection<double>> points, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPointsInPolygon(coordinates, points, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<object>> TIMM.GPS.ControlCenter.LocationService.LocationService.EndPointsInPolygon(System.IAsyncResult result) {
            return base.Channel.EndPointsInPolygon(result);
        }
        
        private System.IAsyncResult OnBeginPointsInPolygon(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<double>> coordinates = ((System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<double>>)(inValues[0]));
            System.Collections.Generic.Dictionary<System.Collections.ObjectModel.ObservableCollection<object>, System.Collections.ObjectModel.ObservableCollection<double>> points = ((System.Collections.Generic.Dictionary<System.Collections.ObjectModel.ObservableCollection<object>, System.Collections.ObjectModel.ObservableCollection<double>>)(inValues[1]));
            return ((TIMM.GPS.ControlCenter.LocationService.LocationService)(this)).BeginPointsInPolygon(coordinates, points, callback, asyncState);
        }
        
        private object[] OnEndPointsInPolygon(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<object>> retVal = ((TIMM.GPS.ControlCenter.LocationService.LocationService)(this)).EndPointsInPolygon(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPointsInPolygonCompleted(object state) {
            if ((this.PointsInPolygonCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PointsInPolygonCompleted(this, new PointsInPolygonCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PointsInPolygonAsync(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<double>> coordinates, System.Collections.Generic.Dictionary<System.Collections.ObjectModel.ObservableCollection<object>, System.Collections.ObjectModel.ObservableCollection<double>> points) {
            this.PointsInPolygonAsync(coordinates, points, null);
        }
        
        public void PointsInPolygonAsync(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<double>> coordinates, System.Collections.Generic.Dictionary<System.Collections.ObjectModel.ObservableCollection<object>, System.Collections.ObjectModel.ObservableCollection<double>> points, object userState) {
            if ((this.onBeginPointsInPolygonDelegate == null)) {
                this.onBeginPointsInPolygonDelegate = new BeginOperationDelegate(this.OnBeginPointsInPolygon);
            }
            if ((this.onEndPointsInPolygonDelegate == null)) {
                this.onEndPointsInPolygonDelegate = new EndOperationDelegate(this.OnEndPointsInPolygon);
            }
            if ((this.onPointsInPolygonCompletedDelegate == null)) {
                this.onPointsInPolygonCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPointsInPolygonCompleted);
            }
            base.InvokeAsync(this.onBeginPointsInPolygonDelegate, new object[] {
                        coordinates,
                        points}, this.onEndPointsInPolygonDelegate, this.onPointsInPolygonCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TIMM.GPS.ControlCenter.LocationService.LocationService.BeginSendMail(string to, string subject, string body, string attachName, byte[] attach, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSendMail(to, subject, body, attachName, attach, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void TIMM.GPS.ControlCenter.LocationService.LocationService.EndSendMail(System.IAsyncResult result) {
            base.Channel.EndSendMail(result);
        }
        
        private System.IAsyncResult OnBeginSendMail(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string to = ((string)(inValues[0]));
            string subject = ((string)(inValues[1]));
            string body = ((string)(inValues[2]));
            string attachName = ((string)(inValues[3]));
            byte[] attach = ((byte[])(inValues[4]));
            return ((TIMM.GPS.ControlCenter.LocationService.LocationService)(this)).BeginSendMail(to, subject, body, attachName, attach, callback, asyncState);
        }
        
        private object[] OnEndSendMail(System.IAsyncResult result) {
            ((TIMM.GPS.ControlCenter.LocationService.LocationService)(this)).EndSendMail(result);
            return null;
        }
        
        private void OnSendMailCompleted(object state) {
            if ((this.SendMailCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SendMailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SendMailAsync(string to, string subject, string body, string attachName, byte[] attach) {
            this.SendMailAsync(to, subject, body, attachName, attach, null);
        }
        
        public void SendMailAsync(string to, string subject, string body, string attachName, byte[] attach, object userState) {
            if ((this.onBeginSendMailDelegate == null)) {
                this.onBeginSendMailDelegate = new BeginOperationDelegate(this.OnBeginSendMail);
            }
            if ((this.onEndSendMailDelegate == null)) {
                this.onEndSendMailDelegate = new EndOperationDelegate(this.OnEndSendMail);
            }
            if ((this.onSendMailCompletedDelegate == null)) {
                this.onSendMailCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendMailCompleted);
            }
            base.InvokeAsync(this.onBeginSendMailDelegate, new object[] {
                        to,
                        subject,
                        body,
                        attachName,
                        attach}, this.onEndSendMailDelegate, this.onSendMailCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override TIMM.GPS.ControlCenter.LocationService.LocationService CreateChannel() {
            return new LocationServiceClientChannel(this);
        }
        
        private class LocationServiceClientChannel : ChannelBase<TIMM.GPS.ControlCenter.LocationService.LocationService>, TIMM.GPS.ControlCenter.LocationService.LocationService {
            
            public LocationServiceClientChannel(System.ServiceModel.ClientBase<TIMM.GPS.ControlCenter.LocationService.LocationService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginPointInPolygon(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<double>> coordinates, System.Collections.ObjectModel.ObservableCollection<double> point, System.Collections.ObjectModel.ObservableCollection<object> gti, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = coordinates;
                _args[1] = point;
                _args[2] = gti;
                System.IAsyncResult _result = base.BeginInvoke("PointInPolygon", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<object> EndPointInPolygon(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<object> _result = ((System.Collections.ObjectModel.ObservableCollection<object>)(base.EndInvoke("PointInPolygon", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPointsInPolygon(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<double>> coordinates, System.Collections.Generic.Dictionary<System.Collections.ObjectModel.ObservableCollection<object>, System.Collections.ObjectModel.ObservableCollection<double>> points, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = coordinates;
                _args[1] = points;
                System.IAsyncResult _result = base.BeginInvoke("PointsInPolygon", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<object>> EndPointsInPolygon(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<object>> _result = ((System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<object>>)(base.EndInvoke("PointsInPolygon", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSendMail(string to, string subject, string body, string attachName, byte[] attach, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[5];
                _args[0] = to;
                _args[1] = subject;
                _args[2] = body;
                _args[3] = attachName;
                _args[4] = attach;
                System.IAsyncResult _result = base.BeginInvoke("SendMail", _args, callback, asyncState);
                return _result;
            }
            
            public void EndSendMail(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("SendMail", _args, result);
            }
        }
    }
}
