//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPS.Website.WebControls.Distribution {
    
    
    public partial class DistributionMap {
        
        /// <summary>
        /// lb_Lower_Classifications control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lb_Lower_Classifications;
        
        /// <summary>
        /// lb_Upper_Classifications control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lb_Upper_Classifications;
        
        /// <summary>
        /// txtTargeting control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtTargeting;
        
        /// <summary>
        /// ctlImportData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GPS.Website.WebControls.ImportData ctlImportData;
        
        /// <summary>
        /// CreateCampaign control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GPS.Website.WebControls.CreateCampaign CreateCampaign;
        
        /// <summary>
        /// ctlLoadAddresses control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GPS.Website.WebControls.LoadAddresses ctlLoadAddresses;
        
        /// <summary>
        /// ctlNewAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GPS.Website.WebControls.NewAddress ctlNewAddress;
        
        /// <summary>
        /// AssignDrivers1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GPS.Website.WebControls.Distribution.AssignDrivers AssignDrivers1;
        
        /// <summary>
        /// AssignAuditors1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GPS.Website.WebControls.Distribution.AssignAuditors AssignAuditors1;
        
        /// <summary>
        /// AssignWalkers1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GPS.Website.WebControls.Distribution.AssignWalkers AssignWalkers1;
        
        /// <summary>
        /// AssignGtus1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GPS.Website.WebControls.Distribution.AssignGtus AssignGtus1;
    }
}
