#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPS.DomainLayer.Entities
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	public partial class GetBGImportedByfilterResult
	{
		
		private int _BlockGroupId;
		
		private string _Total;
		
		private string _Percentage;
		
		public GetBGImportedByfilterResult()
		{
		}
		
		[Column(Storage="_BlockGroupId", DbType="Int NOT NULL")]
		public int BlockGroupId
		{
			get
			{
				return this._BlockGroupId;
			}
			set
			{
				if ((this._BlockGroupId != value))
				{
					this._BlockGroupId = value;
				}
			}
		}
		
		[Column(Storage="_Total", DbType="VarChar(8)")]
		public string Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[Column(Storage="_Percentage", DbType="VarChar(8)")]
		public string Percentage
		{
			get
			{
				return this._Percentage;
			}
			set
			{
				if ((this._Percentage != value))
				{
					this._Percentage = value;
				}
			}
		}
	}
	
	public partial class GetTractImportedByfilterResult
	{
		
		private int _TractId;
		
		private string _Total;
		
		private string _Percentage;
		
		public GetTractImportedByfilterResult()
		{
		}
		
		[Column(Storage="_TractId", DbType="Int NOT NULL")]
		public int TractId
		{
			get
			{
				return this._TractId;
			}
			set
			{
				if ((this._TractId != value))
				{
					this._TractId = value;
				}
			}
		}
		
		[Column(Storage="_Total", DbType="VarChar(8)")]
		public string Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[Column(Storage="_Percentage", DbType="VarChar(8)")]
		public string Percentage
		{
			get
			{
				return this._Percentage;
			}
			set
			{
				if ((this._Percentage != value))
				{
					this._Percentage = value;
				}
			}
		}
	}
	
	public partial class GetBlockGroupMappingsByfilterResult
	{
		
		private int _Id;
		
		private int _ThreeZipAreaId;
		
		private string _ThreeZipAreaCode;
		
		private int _FiveZipAreaId;
		
		private string _FiveZipAreaCode;
		
		private int _TractId;
		
		private string _TractCode;
		
		private int _BlockGroupId;
		
		private string _BlockGroupCode;
		
		private string _Total;
		
		private string _Percentage;
		
		public GetBlockGroupMappingsByfilterResult()
		{
		}
		
		[Column(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[Column(Storage="_ThreeZipAreaId", DbType="Int NOT NULL")]
		public int ThreeZipAreaId
		{
			get
			{
				return this._ThreeZipAreaId;
			}
			set
			{
				if ((this._ThreeZipAreaId != value))
				{
					this._ThreeZipAreaId = value;
				}
			}
		}
		
		[Column(Storage="_ThreeZipAreaCode", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string ThreeZipAreaCode
		{
			get
			{
				return this._ThreeZipAreaCode;
			}
			set
			{
				if ((this._ThreeZipAreaCode != value))
				{
					this._ThreeZipAreaCode = value;
				}
			}
		}
		
		[Column(Storage="_FiveZipAreaId", DbType="Int NOT NULL")]
		public int FiveZipAreaId
		{
			get
			{
				return this._FiveZipAreaId;
			}
			set
			{
				if ((this._FiveZipAreaId != value))
				{
					this._FiveZipAreaId = value;
				}
			}
		}
		
		[Column(Storage="_FiveZipAreaCode", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string FiveZipAreaCode
		{
			get
			{
				return this._FiveZipAreaCode;
			}
			set
			{
				if ((this._FiveZipAreaCode != value))
				{
					this._FiveZipAreaCode = value;
				}
			}
		}
		
		[Column(Storage="_TractId", DbType="Int NOT NULL")]
		public int TractId
		{
			get
			{
				return this._TractId;
			}
			set
			{
				if ((this._TractId != value))
				{
					this._TractId = value;
				}
			}
		}
		
		[Column(Storage="_TractCode", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string TractCode
		{
			get
			{
				return this._TractCode;
			}
			set
			{
				if ((this._TractCode != value))
				{
					this._TractCode = value;
				}
			}
		}
		
		[Column(Storage="_BlockGroupId", DbType="Int NOT NULL")]
		public int BlockGroupId
		{
			get
			{
				return this._BlockGroupId;
			}
			set
			{
				if ((this._BlockGroupId != value))
				{
					this._BlockGroupId = value;
				}
			}
		}
		
		[Column(Storage="_BlockGroupCode", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string BlockGroupCode
		{
			get
			{
				return this._BlockGroupCode;
			}
			set
			{
				if ((this._BlockGroupCode != value))
				{
					this._BlockGroupCode = value;
				}
			}
		}
		
		[Column(Storage="_Total", DbType="VarChar(8)")]
		public string Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[Column(Storage="_Percentage", DbType="VarChar(8)")]
		public string Percentage
		{
			get
			{
				return this._Percentage;
			}
			set
			{
				if ((this._Percentage != value))
				{
					this._Percentage = value;
				}
			}
		}
	}
	
	public partial class GetBlockGroupsByBoxIdResult
	{
		
		private int _Id;
		
		private string _Name;
		
		private string _Code;
		
		private string _StateCode;
		
		private string _CountyCode;
		
		private string _TractCode;
		
		private string _LSAD;
		
		private string _LSADTrans;
		
		private double _MinLongitude;
		
		private double _MaxLongitude;
		
		private double _MinLatitude;
		
		private double _MaxLatitude;
		
		private double _Latitude;
		
		private double _Longitude;
		
		public GetBlockGroupsByBoxIdResult()
		{
		}
		
		[Column(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[Column(Storage="_Code", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[Column(Storage="_StateCode", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string StateCode
		{
			get
			{
				return this._StateCode;
			}
			set
			{
				if ((this._StateCode != value))
				{
					this._StateCode = value;
				}
			}
		}
		
		[Column(Storage="_CountyCode", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string CountyCode
		{
			get
			{
				return this._CountyCode;
			}
			set
			{
				if ((this._CountyCode != value))
				{
					this._CountyCode = value;
				}
			}
		}
		
		[Column(Storage="_TractCode", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string TractCode
		{
			get
			{
				return this._TractCode;
			}
			set
			{
				if ((this._TractCode != value))
				{
					this._TractCode = value;
				}
			}
		}
		
		[Column(Storage="_LSAD", DbType="NVarChar(8)")]
		public string LSAD
		{
			get
			{
				return this._LSAD;
			}
			set
			{
				if ((this._LSAD != value))
				{
					this._LSAD = value;
				}
			}
		}
		
		[Column(Storage="_LSADTrans", DbType="NVarChar(64)")]
		public string LSADTrans
		{
			get
			{
				return this._LSADTrans;
			}
			set
			{
				if ((this._LSADTrans != value))
				{
					this._LSADTrans = value;
				}
			}
		}
		
		[Column(Storage="_MinLongitude", DbType="Float NOT NULL")]
		public double MinLongitude
		{
			get
			{
				return this._MinLongitude;
			}
			set
			{
				if ((this._MinLongitude != value))
				{
					this._MinLongitude = value;
				}
			}
		}
		
		[Column(Storage="_MaxLongitude", DbType="Float NOT NULL")]
		public double MaxLongitude
		{
			get
			{
				return this._MaxLongitude;
			}
			set
			{
				if ((this._MaxLongitude != value))
				{
					this._MaxLongitude = value;
				}
			}
		}
		
		[Column(Storage="_MinLatitude", DbType="Float NOT NULL")]
		public double MinLatitude
		{
			get
			{
				return this._MinLatitude;
			}
			set
			{
				if ((this._MinLatitude != value))
				{
					this._MinLatitude = value;
				}
			}
		}
		
		[Column(Storage="_MaxLatitude", DbType="Float NOT NULL")]
		public double MaxLatitude
		{
			get
			{
				return this._MaxLatitude;
			}
			set
			{
				if ((this._MaxLatitude != value))
				{
					this._MaxLatitude = value;
				}
			}
		}
		
		[Column(Storage="_Latitude", DbType="Float NOT NULL")]
		public double Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this._Latitude = value;
				}
			}
		}
		
		[Column(Storage="_Longitude", DbType="Float NOT NULL")]
		public double Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this._Longitude = value;
				}
			}
		}
	}
	
	public partial class GetBoxMappingsByfilterResult
	{
		
		private int _Id;
		
		private int _ThreeZipAreaId;
		
		private string _ThreeZipAreaCode;
		
		private int _FiveZipAreaId;
		
		private string _FiveZipAreaCode;
		
		private int _TractId;
		
		private string _TractCode;
		
		private int _BlockGroupId;
		
		private string _BlockGroupCode;
		
		private int _BoxId;
		
		private string _Total;
		
		private string _Percentage;
		
		public GetBoxMappingsByfilterResult()
		{
		}
		
		[Column(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[Column(Storage="_ThreeZipAreaId", DbType="Int NOT NULL")]
		public int ThreeZipAreaId
		{
			get
			{
				return this._ThreeZipAreaId;
			}
			set
			{
				if ((this._ThreeZipAreaId != value))
				{
					this._ThreeZipAreaId = value;
				}
			}
		}
		
		[Column(Storage="_ThreeZipAreaCode", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string ThreeZipAreaCode
		{
			get
			{
				return this._ThreeZipAreaCode;
			}
			set
			{
				if ((this._ThreeZipAreaCode != value))
				{
					this._ThreeZipAreaCode = value;
				}
			}
		}
		
		[Column(Storage="_FiveZipAreaId", DbType="Int NOT NULL")]
		public int FiveZipAreaId
		{
			get
			{
				return this._FiveZipAreaId;
			}
			set
			{
				if ((this._FiveZipAreaId != value))
				{
					this._FiveZipAreaId = value;
				}
			}
		}
		
		[Column(Storage="_FiveZipAreaCode", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string FiveZipAreaCode
		{
			get
			{
				return this._FiveZipAreaCode;
			}
			set
			{
				if ((this._FiveZipAreaCode != value))
				{
					this._FiveZipAreaCode = value;
				}
			}
		}
		
		[Column(Storage="_TractId", DbType="Int NOT NULL")]
		public int TractId
		{
			get
			{
				return this._TractId;
			}
			set
			{
				if ((this._TractId != value))
				{
					this._TractId = value;
				}
			}
		}
		
		[Column(Storage="_TractCode", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string TractCode
		{
			get
			{
				return this._TractCode;
			}
			set
			{
				if ((this._TractCode != value))
				{
					this._TractCode = value;
				}
			}
		}
		
		[Column(Storage="_BlockGroupId", DbType="Int NOT NULL")]
		public int BlockGroupId
		{
			get
			{
				return this._BlockGroupId;
			}
			set
			{
				if ((this._BlockGroupId != value))
				{
					this._BlockGroupId = value;
				}
			}
		}
		
		[Column(Storage="_BlockGroupCode", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string BlockGroupCode
		{
			get
			{
				return this._BlockGroupCode;
			}
			set
			{
				if ((this._BlockGroupCode != value))
				{
					this._BlockGroupCode = value;
				}
			}
		}
		
		[Column(Storage="_BoxId", DbType="Int NOT NULL")]
		public int BoxId
		{
			get
			{
				return this._BoxId;
			}
			set
			{
				if ((this._BoxId != value))
				{
					this._BoxId = value;
				}
			}
		}
		
		[Column(Storage="_Total", DbType="VarChar(8)")]
		public string Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[Column(Storage="_Percentage", DbType="VarChar(8)")]
		public string Percentage
		{
			get
			{
				return this._Percentage;
			}
			set
			{
				if ((this._Percentage != value))
				{
					this._Percentage = value;
				}
			}
		}
	}
	
	public partial class GetFiveZipImportedByfilterResult
	{
		
		private int _FiveZipAreaId;
		
		private string _Total;
		
		private string _Percentage;
		
		public GetFiveZipImportedByfilterResult()
		{
		}
		
		[Column(Storage="_FiveZipAreaId", DbType="Int NOT NULL")]
		public int FiveZipAreaId
		{
			get
			{
				return this._FiveZipAreaId;
			}
			set
			{
				if ((this._FiveZipAreaId != value))
				{
					this._FiveZipAreaId = value;
				}
			}
		}
		
		[Column(Storage="_Total", DbType="VarChar(8)")]
		public string Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[Column(Storage="_Percentage", DbType="VarChar(8)")]
		public string Percentage
		{
			get
			{
				return this._Percentage;
			}
			set
			{
				if ((this._Percentage != value))
				{
					this._Percentage = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
